// Compiled shader for Windows, Mac, Linux

//////////////////////////////////////////////////////////////////////////
// 
// NOTE: This is *not* a valid shader file, the contents are provided just
// for information and for debugging purposes only.
// 
//////////////////////////////////////////////////////////////////////////
// Skipping shader variants that would not be included into build of current scene.

Shader "Shader Graphs/SeeThroughShader" {
Properties {
[NoScaleOffset]  _MainTexture ("_MainTexture", 2D) = "white" { }
 _Tint ("_Tint", Color) = (0.000000,0.000000,0.000000,0.000000)
 _EntityPosition ("_EntityPosition", Vector) = (0.650000,0.650000,0.000000,0.000000)
 _Size ("_Size", Float) = 1.000000
 _Smoothness ("_Smoothness", Range(0.000000,1.000000)) = 0.500000
[HideInInspector]  _QueueOffset ("_QueueOffset", Float) = 0.000000
[HideInInspector]  _QueueControl ("_QueueControl", Float) = -1.000000
[HideInInspector] [NoScaleOffset]  unity_Lightmaps ("unity_Lightmaps", 2DArray) = "" { }
[HideInInspector] [NoScaleOffset]  unity_LightmapsInd ("unity_LightmapsInd", 2DArray) = "" { }
[HideInInspector] [NoScaleOffset]  unity_ShadowMasks ("unity_ShadowMasks", 2DArray) = "" { }
}
SubShader { 
 Tags { "QUEUE"="Transparent" "RenderType"="Transparent" "DisableBatching"="False" "RenderPipeline"="UniversalPipeline" "UniversalMaterialType"="Unlit" "ShaderGraphShader"="true" "ShaderGraphTargetId"="UniversalUnlitSubTarget" }


 // Stats for Vertex shader:
 //        d3d11: 15 math
 // Stats for Fragment shader:
 //        d3d11: 21 math
 Pass {
  Name "Universal Forward"
  Tags { "QUEUE"="Transparent" "RenderType"="Transparent" "DisableBatching"="False" "RenderPipeline"="UniversalPipeline" "UniversalMaterialType"="Unlit" "ShaderGraphShader"="true" "ShaderGraphTargetId"="UniversalUnlitSubTarget" }
  ZWrite On
  Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 15 math, 2 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord0"

Constant Buffer "$Globals" (2080 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1248
}
Constant Buffer "UnityPerDraw" (720 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float       
// TEXCOORD                 0   xyzw        3     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// INTERP                   0   xyzw        1     NONE   float   xyzw
// INTERP                   1   xyz         2     NONE   float   xyz 
// INTERP                   2   xyz         3     NONE   float   xyz 
//
      vs_4_0
      dcl_constantbuffer CB0[82], immediateIndexed
      dcl_constantbuffer CB1[7], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_input v3.xyzw
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyzw
      dcl_output o2.xyz
      dcl_output o3.xyz
      dcl_temps 2
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: mul r1.xyzw, r0.yyyy, cb0[79].xyzw
   5: mad r1.xyzw, cb0[78].xyzw, r0.xxxx, r1.xyzw
   6: mad r1.xyzw, cb0[80].xyzw, r0.zzzz, r1.xyzw
   7: mov o2.xyz, r0.xyzx
   8: add o0.xyzw, r1.xyzw, cb0[81].xyzw
   9: mov o1.xyzw, v3.xyzw
  10: dp3 r0.x, v1.xyzx, cb1[4].xyzx
  11: dp3 r0.y, v1.xyzx, cb1[5].xyzx
  12: dp3 r0.z, v1.xyzx, cb1[6].xyzx
  13: dp3 r0.w, r0.xyzx, r0.xyzx
  14: max r0.w, r0.w, l(0.000000)
  15: rsq r0.w, r0.w
  16: mul o3.xyz, r0.wwww, r0.xyzx
  17: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 21 math, 2 temp registers
Set 2D Texture "_MainTexture" to slot 0

Constant Buffer "$Globals" (2080 bytes) on slot 0 {
  Vector4 _ScaledScreenParams at 48
  Vector2 _GlobalMipBias at 64
  Vector4 _ProjectionParams at 352
  Vector4 unity_OrthoParams at 400
}
Constant Buffer "UnityPerMaterial" (112 bytes) on slot 1 {
  Vector4 _Tint at 16
  Vector2 _EntityPosition at 32
  Float _Size at 40
  Float _Smoothness at 44
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xy  
// INTERP                   0   xyzw        1     NONE   float   xy  
// INTERP                   1   xyz         2     NONE   float       
// INTERP                   2   xyz         3     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_constantbuffer CB0[26], immediateIndexed
      dcl_constantbuffer CB1[3], immediateIndexed
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input_ps_siv linear noperspective v0.xy, position
      dcl_input_ps linear v1.xy
      dcl_output o0.xyzw
      dcl_temps 2
   0: lt r0.x, cb0[22].x, l(0.000000)
   1: add r0.y, -v0.y, cb0[3].y
   2: movc r0.y, r0.x, r0.y, v0.y
   3: mov r0.x, v0.x
   4: div r0.xy, r0.xyxx, cb0[3].xyxx
   5: add r0.z, -r0.y, l(1.000000)
   6: add r0.xy, r0.xzxx, r0.xzxx
   7: mad r0.xy, cb1[2].xyxx, l(-1.500000, -1.500000, 0.000000, 0.000000), r0.xyxx
   8: add r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
   9: mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  10: div r0.z, cb0[25].y, cb0[25].x
  11: mul r1.x, r0.z, cb1[2].z
  12: mov r1.y, cb1[2].z
  13: div r0.xy, r0.xyxx, r1.xyxx
  14: dp2 r0.x, r0.xyxx, r0.xyxx
  15: sqrt r0.x, r0.x
  16: add r0.x, -r0.x, l(1.000000)
  17: max r0.x, r0.x, l(0.000000)
  18: div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), cb1[2].w
  19: mul_sat r0.x, r0.y, r0.x
  20: mad r0.y, r0.x, l(-2.000000), l(3.000000)
  21: mul r0.x, r0.x, r0.x
  22: mad o0.w, -r0.y, r0.x, l(1.000000)
  23: sample_b r0.xyzw, v1.xyxx, t0.xyzw, s0, cb0[4].x
  24: mul o0.xyz, r0.xyzx, cb1[1].xyzx
  25: ret 
// Approximately 0 instruction slots used


 }


 // Stats for Vertex shader:
 //        d3d11: 22 math, 2 branch
 // Stats for Fragment shader:
 //        d3d11: 7 math
 Pass {
  Name "MotionVectors"
  Tags { "LIGHTMODE"="MOTIONVECTORS" "QUEUE"="Transparent" "RenderType"="Transparent" "DisableBatching"="False" "RenderPipeline"="UniversalPipeline" "UniversalMaterialType"="Unlit" "ShaderGraphShader"="true" "ShaderGraphTargetId"="UniversalUnlitSubTarget" }
  ColorMask RG
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 22 math, 3 temp registers, 2 branches
Uses vertex data channel "Vertex"
Uses vertex data channel "TexCoord4"

Constant Buffer "$Globals" (2080 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1248
  Matrix4x4 _PrevViewProjMatrix at 1424
  Matrix4x4 _NonJitteredViewProjMatrix at 1488
}
Constant Buffer "UnityPerDraw" (720 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_MatrixPreviousM at 544
  Vector4 unity_MotionVectorsParams at 672
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// TEXCOORD                 4   xyz         1     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// CLIP_POSITION_NO_JITTER     0   xyz         0     NONE   float   xyz 
// PREVIOUS_CLIP_POSITION_NO_JITTER     0   xyz         1     NONE   float   xyz 
// SV_POSITION              0   xyzw        2      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[97], immediateIndexed
      dcl_constantbuffer CB1[43], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_output o0.xyz
      dcl_output o1.xyz
      dcl_output_siv o2.xyzw, position
      dcl_temps 3
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: mul r1.xyzw, r0.yyyy, cb0[79].xyzw
   5: mad r1.xyzw, cb0[78].xyzw, r0.xxxx, r1.xyzw
   6: mad r1.xyzw, cb0[80].xyzw, r0.zzzz, r1.xyzw
   7: add o2.xyzw, r1.xyzw, cb0[81].xyzw
   8: ne r0.w, cb1[42].y, l(0.000000)
   9: if_nz r0.w
  10:   eq r0.w, cb1[42].x, l(1.000000)
  11:   movc r1.xyz, r0.wwww, v1.xyzx, v0.xyzx
  12:   mul r2.xyz, r0.yyyy, cb0[94].xywx
  13:   mad r0.xyw, cb0[93].xyxw, r0.xxxx, r2.xyxz
  14:   mad r0.xyz, cb0[95].xywx, r0.zzzz, r0.xywx
  15:   add o0.xyz, r0.xyzx, cb0[96].xywx
  16:   mul r0.xyzw, r1.yyyy, cb1[35].xyzw
  17:   mad r0.xyzw, cb1[34].xyzw, r1.xxxx, r0.xyzw
  18:   mad r0.xyzw, cb1[36].xyzw, r1.zzzz, r0.xyzw
  19:   add r0.xyzw, r0.xyzw, cb1[37].xyzw
  20:   mul r1.xyz, r0.yyyy, cb0[90].xywx
  21:   mad r1.xyz, cb0[89].xywx, r0.xxxx, r1.xyzx
  22:   mad r0.xyz, cb0[91].xywx, r0.zzzz, r1.xyzx
  23:   mad o1.xyz, cb0[92].xywx, r0.wwww, r0.xyzx
  24: else 
  25:   mov o0.xyz, l(0,0,0,0)
  26:   mov o1.xyz, l(0,0,0,0)
  27: endif 
  28: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 7 math, 1 temp registers
Constant Buffer "UnityPerDraw" (720 bytes) on slot 0 {
  Vector4 unity_MotionVectorsParams at 672
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// CLIP_POSITION_NO_JITTER     0   xyz         0     NONE   float   xyz 
// PREVIOUS_CLIP_POSITION_NO_JITTER     0   xyz         1     NONE   float   xyz 
// SV_POSITION              0   xyzw        2      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_constantbuffer CB0[43], immediateIndexed
      dcl_input_ps linear v0.xyz
      dcl_input_ps linear v1.xyz
      dcl_output o0.xyzw
      dcl_temps 1
   0: div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), v1.z
   1: mul r0.xy, r0.xxxx, v1.xyxx
   2: div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), v0.z
   3: mad r0.xy, v0.xyxx, r0.zzzz, -r0.xyxx
   4: mul r0.xy, r0.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000)
   5: ne r0.z, cb0[42].y, l(0.000000)
   6: and o0.xy, r0.xyxx, r0.zzzz
   7: mov o0.zw, l(0,0,0,0)
   8: ret 
// Approximately 0 instruction slots used


 }


 // Stats for Vertex shader:
 //        d3d11: 15 math
 // Stats for Fragment shader:
 //        d3d11: 3 math
 Pass {
  Name "DepthNormalsOnly"
  Tags { "LIGHTMODE"="DepthNormalsOnly" "QUEUE"="Transparent" "RenderType"="Transparent" "DisableBatching"="False" "RenderPipeline"="UniversalPipeline" "UniversalMaterialType"="Unlit" "ShaderGraphShader"="true" "ShaderGraphTargetId"="UniversalUnlitSubTarget" }
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 15 math, 2 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"

Constant Buffer "$Globals" (2080 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1248
}
Constant Buffer "UnityPerDraw" (720 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// INTERP                   0   xyz         1     NONE   float   xyz 
//
      vs_4_0
      dcl_constantbuffer CB0[82], immediateIndexed
      dcl_constantbuffer CB1[7], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_temps 2
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: mul r1.xyzw, r0.yyyy, cb0[79].xyzw
   5: mad r1.xyzw, cb0[78].xyzw, r0.xxxx, r1.xyzw
   6: mad r0.xyzw, cb0[80].xyzw, r0.zzzz, r1.xyzw
   7: add o0.xyzw, r0.xyzw, cb0[81].xyzw
   8: dp3 r0.x, v1.xyzx, cb1[4].xyzx
   9: dp3 r0.y, v1.xyzx, cb1[5].xyzx
  10: dp3 r0.z, v1.xyzx, cb1[6].xyzx
  11: dp3 r0.w, r0.xyzx, r0.xyzx
  12: max r0.w, r0.w, l(0.000000)
  13: rsq r0.w, r0.w
  14: mul o1.xyz, r0.wwww, r0.xyzx
  15: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 3 math, 1 temp registers
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// INTERP                   0   xyz         1     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_input_ps linear v1.xyz
      dcl_output o0.xyzw
      dcl_temps 1
   0: dp3 r0.x, v1.xyzx, v1.xyzx
   1: rsq r0.x, r0.x
   2: mul o0.xyz, r0.xxxx, v1.xyzx
   3: mov o0.w, l(0)
   4: ret 
// Approximately 0 instruction slots used


 }


 // Stats for Vertex shader:
 //        d3d11: 28 avg math (26..30)
 Pass {
  Name "ShadowCaster"
  Tags { "LIGHTMODE"="SHADOWCASTER" "QUEUE"="Transparent" "RenderType"="Transparent" "DisableBatching"="False" "RenderPipeline"="UniversalPipeline" "UniversalMaterialType"="Unlit" "ShaderGraphShader"="true" "ShaderGraphTargetId"="UniversalUnlitSubTarget" }
  ColorMask 0
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 26 math, 2 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"

Constant Buffer "$Globals" (2112 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1248
  Vector4 _ShadowBias at 2064
  Vector3 _LightDirection at 2080
}
Constant Buffer "UnityPerDraw" (720 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// INTERP                   0   xyz         1     NONE   float   xyz 
//
      vs_4_0
      dcl_constantbuffer CB0[131], immediateIndexed
      dcl_constantbuffer CB1[7], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_temps 2
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: mad r0.xyz, cb0[130].xyzx, cb0[129].xxxx, r0.xyzx
   5: dp3 r1.x, v1.xyzx, cb1[4].xyzx
   6: dp3 r1.y, v1.xyzx, cb1[5].xyzx
   7: dp3 r1.z, v1.xyzx, cb1[6].xyzx
   8: dp3 r0.w, r1.xyzx, r1.xyzx
   9: max r0.w, r0.w, l(0.000000)
  10: rsq r0.w, r0.w
  11: mul r1.xyz, r0.wwww, r1.xyzx
  12: dp3_sat r0.w, cb0[130].xyzx, r1.xyzx
  13: add r0.w, -r0.w, l(1.000000)
  14: mul r0.w, r0.w, cb0[129].y
  15: mad r0.xyz, r1.xyzx, r0.wwww, r0.xyzx
  16: mov o1.xyz, r1.xyzx
  17: mul r1.xyzw, r0.yyyy, cb0[79].xyzw
  18: mad r1.xyzw, cb0[78].xyzw, r0.xxxx, r1.xyzw
  19: mad r0.xyzw, cb0[80].xyzw, r0.zzzz, r1.xyzw
  20: add r0.xyzw, r0.xyzw, cb0[81].xyzw
  21: min r1.x, r0.w, r0.z
  22: add r1.x, -r0.z, r1.x
  23: round_ne r1.y, cb0[129].z
  24: eq r1.y, r1.y, l(1.000000)
  25: and r1.y, r1.y, l(0x3f800000)
  26: mad o0.z, r1.y, r1.x, r0.z
  27: mov o0.xyw, r0.xyxw
  28: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// INTERP                   0   xyz         1     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords: _CASTING_PUNCTUAL_LIGHT_SHADOW
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 30 math, 3 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"

Constant Buffer "$Globals" (2112 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1248
  Vector4 _ShadowBias at 2064
  Vector3 _LightPosition at 2096
}
Constant Buffer "UnityPerDraw" (720 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// INTERP                   0   xyz         1     NONE   float   xyz 
//
      vs_4_0
      dcl_constantbuffer CB0[132], immediateIndexed
      dcl_constantbuffer CB1[7], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_temps 3
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: add r1.xyz, -r0.xyzx, cb0[131].xyzx
   5: dp3 r0.w, r1.xyzx, r1.xyzx
   6: rsq r0.w, r0.w
   7: mul r1.xyz, r0.wwww, r1.xyzx
   8: mad r0.xyz, r1.xyzx, cb0[129].xxxx, r0.xyzx
   9: dp3 r2.x, v1.xyzx, cb1[4].xyzx
  10: dp3 r2.y, v1.xyzx, cb1[5].xyzx
  11: dp3 r2.z, v1.xyzx, cb1[6].xyzx
  12: dp3 r0.w, r2.xyzx, r2.xyzx
  13: max r0.w, r0.w, l(0.000000)
  14: rsq r0.w, r0.w
  15: mul r2.xyz, r0.wwww, r2.xyzx
  16: dp3_sat r0.w, r1.xyzx, r2.xyzx
  17: add r0.w, -r0.w, l(1.000000)
  18: mul r0.w, r0.w, cb0[129].y
  19: mad r0.xyz, r2.xyzx, r0.wwww, r0.xyzx
  20: mov o1.xyz, r2.xyzx
  21: mul r1.xyzw, r0.yyyy, cb0[79].xyzw
  22: mad r1.xyzw, cb0[78].xyzw, r0.xxxx, r1.xyzw
  23: mad r0.xyzw, cb0[80].xyzw, r0.zzzz, r1.xyzw
  24: add r0.xyzw, r0.xyzw, cb0[81].xyzw
  25: min r1.x, r0.w, r0.z
  26: add r1.x, -r0.z, r1.x
  27: round_ne r1.y, cb0[129].z
  28: eq r1.y, r1.y, l(1.000000)
  29: and r1.y, r1.y, l(0x3f800000)
  30: mad o0.z, r1.y, r1.x, r0.z
  31: mov o0.xyw, r0.xyxw
  32: ret 
// Approximately 0 instruction slots used


-- Fragment shader for "d3d11":
// No shader variant for this keyword set. The closest match will be used instead.

 }


 // Stats for Vertex shader:
 //        d3d11: 15 math
 // Stats for Fragment shader:
 //        d3d11: 4 math
 Pass {
  Name "GBuffer"
  Tags { "LIGHTMODE"="UniversalGBuffer" "QUEUE"="Transparent" "RenderType"="Transparent" "DisableBatching"="False" "RenderPipeline"="UniversalPipeline" "UniversalMaterialType"="Unlit" "ShaderGraphShader"="true" "ShaderGraphTargetId"="UniversalUnlitSubTarget" }
  ZWrite Off
  Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 15 math, 2 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord0"

Constant Buffer "$Globals" (2080 bytes) on slot 0 {
  Matrix4x4 unity_MatrixVP at 1248
}
Constant Buffer "UnityPerDraw" (720 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float       
// TEXCOORD                 0   xyzw        3     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// INTERP                   0   xyz         1     NONE   float   xyz 
// INTERP                   2   xyzw        2     NONE   float   xyzw
// INTERP                   3   xyz         3     NONE   float   xyz 
// INTERP                   4   xyz         4     NONE   float   xyz 
//
      vs_5_0
      dcl_globalFlags refactoringAllowed
      dcl_constantbuffer CB0[82], immediateIndexed
      dcl_constantbuffer CB1[7], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyz
      dcl_input v3.xyzw
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_output o2.xyzw
      dcl_output o3.xyz
      dcl_output o4.xyz
      dcl_temps 2
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: add r0.xyz, r0.xyzx, cb1[3].xyzx
   4: mul r1.xyzw, r0.yyyy, cb0[79].xyzw
   5: mad r1.xyzw, cb0[78].xyzw, r0.xxxx, r1.xyzw
   6: mad r1.xyzw, cb0[80].xyzw, r0.zzzz, r1.xyzw
   7: mov o3.xyz, r0.xyzx
   8: add o0.xyzw, r1.xyzw, cb0[81].xyzw
   9: mov o1.xyz, l(0,0,0,0)
  10: mov o2.xyzw, v3.xyzw
  11: dp3 r0.x, v1.xyzx, cb1[4].xyzx
  12: dp3 r0.y, v1.xyzx, cb1[5].xyzx
  13: dp3 r0.z, v1.xyzx, cb1[6].xyzx
  14: dp3 r0.w, r0.xyzx, r0.xyzx
  15: max r0.w, r0.w, l(0.000000)
  16: rsq r0.w, r0.w
  17: mul o4.xyz, r0.wwww, r0.xyzx
  18: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 4 math, 1 temp registers
Set 2D Texture "_MainTexture" to slot 0

Constant Buffer "$Globals" (2080 bytes) on slot 0 {
  Vector2 _GlobalMipBias at 64
}
Constant Buffer "UnityPerMaterial" (112 bytes) on slot 1 {
  Vector4 _Tint at 16
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// INTERP                   0   xyz         1     NONE   float       
// INTERP                   2   xyzw        2     NONE   float   xy  
// INTERP                   3   xyz         3     NONE   float       
// INTERP                   4   xyz         4     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
//
      ps_5_0
      dcl_globalFlags refactoringAllowed
      dcl_constantbuffer CB0[5], immediateIndexed
      dcl_constantbuffer CB1[2], immediateIndexed
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input_ps linear v2.xy
      dcl_input_ps linear v4.xyz
      dcl_output o0.xyzw
      dcl_output o1.xyzw
      dcl_output o2.xyzw
      dcl_output o3.xyzw
      dcl_temps 1
   0: sample_b_indexable(texture2d)(float,float,float,float) r0.xyz, v2.xyxx, t0.xyzw, s0, cb0[4].x
   1: mul o0.xyz, r0.xyzx, cb1[1].xyzx
   2: mov o0.w, l(0)
   3: mov o1.xyzw, l(0,0,0,1.000000)
   4: dp3 r0.x, v4.xyzx, v4.xyzx
   5: rsq r0.x, r0.x
   6: mul o2.xyz, r0.xxxx, v4.xyzx
   7: mov o2.w, l(0)
   8: mov o3.xyzw, l(0,0,0,1.000000)
   9: ret 
// Approximately 0 instruction slots used


 }
}
CustomEditor "UnityEditor.ShaderGraph.GenericShaderGraphMaterialGUI"
Fallback "Hidden/Shader Graph/FallbackError"
}